# Generated by Django 5.2.5 on 2025-08-24 21:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticator', '0001_initial'),
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('planned', 'planned'), ('in-progress', 'in-progress'), ('onleave', 'onleave'), ('finished', 'finished'), ('cancelled', 'cancelled')], default='in-progress', max_length=20)),
                ('klass', models.CharField(choices=[('AMB', 'Ambulatory'), ('IMP', 'Inpatient'), ('EMER', 'Emergency'), ('VR', 'Virtual'), ('HH', 'Home Health')], default='AMB', max_length=10, verbose_name='class')),
                ('type', models.JSONField(blank=True, default=list)),
                ('period', models.JSONField(blank=True, default=dict)),
                ('reasonCode', models.JSONField(blank=True, default=list)),
                ('note', models.TextField(blank=True)),
                ('participant_practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authenticator.practitioner')),
                ('serviceProvider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
