# Generated by Django 5.2.5 on 2025-08-24 21:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticator', '0001_initial'),
        ('encounters', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.JSONField(default=dict)),
                ('status', models.CharField(default='active', max_length=20)),
                ('form', models.JSONField(blank=True, default=dict)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('on-hold', 'on-hold'), ('cancelled', 'cancelled'), ('completed', 'completed'), ('entered-in-error', 'entered-in-error'), ('stopped', 'stopped'), ('draft', 'draft')], default='active', max_length=20)),
                ('intent', models.CharField(choices=[('proposal', 'proposal'), ('plan', 'plan'), ('order', 'order'), ('original-order', 'original-order'), ('reflex-order', 'reflex-order'), ('filler-order', 'filler-order'), ('instance-order', 'instance-order'), ('option', 'option')], default='order', max_length=30)),
                ('medicationText', models.CharField(blank=True, max_length=255)),
                ('authoredOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('dosageInstruction', models.JSONField(blank=True, default=list)),
                ('dispenseRequest', models.JSONField(blank=True, default=dict)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_requests', to='encounters.encounter')),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medications.medication')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authenticator.practitioner')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_requests', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
