# Generated by Django 5.2.5 on 2025-08-24 21:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticator', '0001_initial'),
        ('encounters', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinicalStatus', models.CharField(choices=[('active', 'active'), ('recurrence', 'recurrence'), ('relapse', 'relapse'), ('inactive', 'inactive'), ('remission', 'remission'), ('resolved', 'resolved')], default='active', max_length=20)),
                ('verificationStatus', models.CharField(choices=[('unconfirmed', 'unconfirmed'), ('provisional', 'provisional'), ('differential', 'differential'), ('confirmed', 'confirmed'), ('refuted', 'refuted'), ('entered-in-error', 'entered-in-error')], default='confirmed', max_length=20)),
                ('category', models.JSONField(blank=True, default=list)),
                ('code', models.JSONField(default=dict)),
                ('onsetDateTime', models.DateTimeField(blank=True, null=True)),
                ('recordedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditions', to='encounters.encounter')),
                ('recorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authenticator.practitioner')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
