# Generated by Django 5.2.5 on 2025-08-24 21:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifiers', models.JSONField(blank=True, default=list)),
                ('name', models.JSONField(blank=True, default=dict)),
                ('telecom', models.JSONField(blank=True, default=list)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('contact', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('managingOrganization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
